// <auto-generated />
using System;
using ECBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECBook.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230921072917_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("ECBook.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateTimePosted")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
                            DateTimePosted = new DateTimeOffset(new DateTime(2020, 11, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
                            DateTimePosted = new DateTimeOffset(new DateTime(2020, 11, 1, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ECBook.Data.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Jane",
                            JobTitle = "Developer",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "John",
                            JobTitle = "Consultant",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Maisie",
                            JobTitle = "Project Manager",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Jack",
                            JobTitle = "Engagement Officer",
                            LastName = "Simpson"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Sadie",
                            JobTitle = "Finance Director",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Pete",
                            JobTitle = "Developer",
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Sinead",
                            JobTitle = "Consultant",
                            LastName = "O'Leary"
                        });
                });

            modelBuilder.Entity("ECBook.Data.Entities.Post", b =>
                {
                    b.HasOne("ECBook.Data.Entities.Profile", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
